name: test config name
description: test config description
sources:
  - repo_url: https://github.com/manosriram-youtube/reddit_backend/tree/master/gateway/protos
    dest_path: vendors/gateway_protos
